---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brush
  namespace: colorz
  labels:
    app: brush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brush
  template:
    metadata:
      labels:
        app: brush
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: colorz
        image: ghcr.io/olix0r/colorwheel:v1
        imagePullPolicy: Always
        env:
          - name: RUST_LOG
            value: info,colorwheel=debug
        args:
          - brush
          - /colorwheel/brush/config.yml
        volumeMounts:
        - name: config-volume
          mountPath: /colorwheel/brush
      volumes:
      - name: config-volume
        configMap:
          name: brush-config
          optional: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: Exists
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: brush
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: brush-config
  namespace: colorz
  labels:
    app: brush
data:
  config.yml: |
    requestsPerSecond: 50
    reportIntervalSeconds: 10
    uri: http://paint.colorz.svc.cluster.local
...
