---
apiVersion: v1
kind: Service
metadata:
  name: paint
  namespace: colorz
  labels:
    mirror.linkerd.io/exported: remote-discovery
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: paint
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paint-config
  namespace: colorz
  labels:
    app: paint
data:
  red.yml: |
    color: "#ff0000"
    averageResponseTime: 0.020
  green.yml: |
    color: "#00ff00"
    averageResponseTime: 0.020
  blue.yml: |
    color: "#0000ff"
    averageResponseTime: 0.020
