## This linkerd-trust-anchor ClusterIssuer uses a certificate stored in the
## linkerd-identity-trust-roots Secret in the cert-manager namespace. This
## requires that both the public and private half of the cert be present!
##
## For anything like production use, you'd reconfigure this ClusterIssuer to
## use an external CA store for security. Storing the trust anchor's secret
## key in the cluster is a bad idea.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-trust-anchor
  namespace: cert-manager
spec:
  ca:
    secretName: linkerd-trust-anchor
