apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:delete-replicasets
  labels:
    rbac.kyverno.io/aggregate-to-cleanup-controller: "true"
rules:
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - delete
  - view
  - list
  - watch
