apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: hazl
servers: 1
agents: 3
network: hazl
ports:
  - port: 80:80
    nodeFilters: [loadbalancer]
  - port: 443:443
    nodeFilters: [loadbalancer]
image: rancher/k3s:v1.32.7-k3s1
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters: [server:*]
      - arg: --debug
        nodeFilters: [server:*]
    nodeLabels:
      - label: topology.kubernetes.io/zone=zone-a
        nodeFilters: [agent:0]
      - label: topology.kubernetes.io/zone=zone-b
        nodeFilters: [agent:1]
      - label: topology.kubernetes.io/zone=zone-c
        nodeFilters: [agent:2]
