apiVersion: workload.linkerd.io/v1alpha1
kind: ExternalWorkload
metadata:
  name: smiley
  namespace: faces
  labels:
    app: smiley
    location: vm
    workload_name: smiley
spec:
  meshTls:
    identity: "spiffe://root.linkerd.cluster.local/smiley"
    serverName: "smiley.cluster.local"
  workloadIPs:
  - ip: 172.31.4.61
  ports:
  - port: 8000
    name: http
status:
  conditions:
    - type: Ready
      status: "True"
      lastTransitionTime: "2024-01-24T11:53:43Z"
      reason: "Alive"
      message: "This workload is alive"
---
apiVersion: v1
kind: Service
metadata:
  name: smiley
  namespace: faces
spec:
  type: ClusterIP
  selector:
    workload_name: smiley
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
