---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  # This is the name of the Issuer resource; it's the way
  # Certificate resources can find this issuer.
  name: identity-issuer-clusterissuer
  namespace: cert-manager
spec:
  ca:
    secretName: linkerd-trust-anchor
