---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: booksapp
  name: webapp
  labels:
    app: webapp
    app.kubernetes.io/part-of: booksapp
    project: booksapp
spec:
  podSelector:
    matchLabels:
      app: webapp
      project: booksapp
  port: service
  proxyProtocol: HTTP/1