---
kind: SMA-cluster
apiVersion: sma.buoyant.io/v1alpha1
metadata:
  name: cdn
spec:
  # subnet is byte-ID/nybble-ID, both in hex. They get used for subnetting, so
  # they must be unique across all clusters in the same group.
  #
  # If IPv6 is enabled, we use fd00:$byteID:1::/64 for pods and
  # fd00:$byteID:2::/112 for services, and we set up MetalLB to carve out a
  # /96 with a prefix of $byteID from the Docker network V6 space.
  #
  # If IPv4 is enabled, we use 10.$byteID.1.0/24 for pods and
  # 10.$byteID.2.0/24 for services. The nybble ID comes in for MetalLB:
  # the Docker network V4 space is likely already a /24, so we use the
  # nybble ID to carve out a /28 from that.

  # "CD" for "CDN", and use "D" because we use "C" for color.
  subnet: CD/D

  v4Enabled: true
  v6Enabled: false  # We can't enable IPv6 for BEL yet.

  # Provider sets what kind of cluster to create.
  provider: k3d
