apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: demo-cluster-topo
servers: 1
agents: 3
network: multiaz-topo
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=servicelb,traefik
        nodeFilters: [server:*]
      - arg: --debug
        nodeFilters: [server:*]
    nodeLabels:
      - label: topology.kubernetes.io/zone=zone-0
        nodeFilters: [agent:0]
      - label: topology.kubernetes.io/zone=zone-1
        nodeFilters: [agent:1]
      - label: topology.kubernetes.io/zone=zone-2
        nodeFilters: [agent:2]
