# linkerd-identity-trust-roots-bundle.yaml
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
spec:
  sources:
  - secret:
      name: "linkerd-identity-trust-roots"
      key: "tls.crt"
  target:
    configMap:
      key: "ca-bundle.crt"
