# tpp-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tpp-issuer
spec:
  venafi:
    zone: \VED\Policy\Certificates\k8s\cluster1  # <- Substitute with your desired policy folder
    tpp:
      url: ${TPP_URL} # <- Substitute with your TPP server API URL
      credentialsRef:
        name: tpp-secret
