apiVersion: apps/v1
kind: Deployment
metadata:
  name: face2
  namespace: faces
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service: face
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        service: face
    spec:
      containers:
      - env:
        - name: FACES_SERVICE
          value: face
        - name: ERROR_FRACTION
          value: "100"
        - name: LATCH_FRACTION
          value: "25"
        image: dwflynn/faces-service:0.8.0
        imagePullPolicy: Always
        name: face
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 300m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
