apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rusty
  annotations:
    description: 'rusty, a WebAssembly component that works with wasmCloud and the Faces demo'
    wasmcloud.dev/authors: Flynn and Bailey Hayes
    wasmcloud.dev/source-url: https://github.com/BuoyantIO/faces-demo/blob/main/rust/rusty/rusty.yaml
    wasmcloud.dev/readme-md-url: https://github.com/BuoyantIO/faces-demo/blob/main/rust/rusty/README.md
    wasmcloud.dev/homepage: https://github.com/BuoyantIO/faces-demo/tree/main/rust/rusty
    wasmcloud.dev/categories: |
      http,http-server,rust,rusty,faces
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: ghcr.io/BuoyantIO/faces-components/rusty:0.1.1
      traits:
        # Govern the spread/scheduling of the component
        - type: daemonscaler
          properties:
            replicas: 100
      # config:
      #   - name: custom-config
      #     properties:
      #       ERROR_FRACTION: 1
      #       DELAY_BUCKETS: 5,10,20

    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
      traits:
        - type: link
          properties:
            namespace: wasi
            package: http
            interfaces:
            - incoming-handler
            source:
              config:
              - name: wasi-http-config
                properties:
                  address: 0.0.0.0:8000
            target:
              name: http-component
        # When running the application on Kubernetes with the wasmCloud operator,
        # the operator automatically creates a Kubernetes service for applications that use
        # the httpserver provider with a daemonscaler.
        - type: spreadscaler
          properties:
            replicas: 1