apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rusty
  annotations:
    description: 'HTTP demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)'
    wasmcloud.dev/authors: wasmCloud team
    wasmcloud.dev/source-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/rust/components/rusty/wadm.yaml
    wasmcloud.dev/readme-md-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/rust/components/rusty/README.md
    wasmcloud.dev/homepage: https://github.com/wasmCloud/wasmCloud/tree/main/examples/rust/components/rusty
    wasmcloud.dev/categories: |
      http,http-server,rust,hello-world,example
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: ghcr.io/BuoyantIO/faces-components/rusty:0.1.1
        # image: ghcr.io/ricochet/components/rusty:0.1.0
        # image: file://./build/http_hello_world_s.wasm
      traits:
        # Govern the spread/scheduling of the component
        - type: daemonscaler
          properties:
            replicas: 100
      config:
        - name: custom-config
          properties:
            SMILEY: HeartEyes
            ERROR_FRACTION: 1
            DELAY_BUCKETS: 5,10,20

    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
      traits:
        - type: link
          properties:
            namespace: wasi
            package: http
            interfaces:
            - incoming-handler
            source:
              config:
              - name: wasi-http-config
                properties:
                  address: 0.0.0.0:8000
            target:
              name: http-component
        # When running the application on Kubernetes with the wasmCloud operator,
        # the operator automatically creates a Kubernetes service for applications that use
        # the httpserver provider with a daemonscaler.
        - type: spreadscaler
          properties:
            replicas: 1