---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: emojivoto-mapping
spec:
  prefix: /
  hostname: emoji.example.com
  service: web-svc.emojivoto
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: emoji-east-mapping
spec:
  prefix: /east-test/
  hostname: emoji.example.com
  service: emoji-svc.emojivoto:8080
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: emoji-west-mapping
spec:
  prefix: /west-test/
  hostname: emoji.example.com
  service: emoji-svc-west.emojivoto:8080
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: books-mapping
spec:
  prefix: /
  hostname: books.example.com
  service: webapp.booksapp:7000
