---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: viz-mapping
spec:
  prefix: /
  hostname: viz.example.com:81
  service: web.linkerd-viz.svc.cluster.local:8084
  host_rewrite: web.linkerd-viz.svc.cluster.local:8084
  remove_request_headers:
  - Origin
  allow_upgrade:
  - websocket