---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: emojivoto-mapping
spec:
  prefix: /
  hostname: emoji.example.com:81
  service: web-svc.emojivoto
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: books-mapping
spec:
  prefix: /
  hostname: books.example.com:81
  service: webapp.booksapp:7000
