---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-oakland
  namespace: orders
  labels:
    color: warehouse-oakland
    app: fulfillment
spec:
  replicas: 3
  selector:
    matchLabels:
      color: warehouse-oakland
      app: fulfillment
  template:
    metadata:
      labels:
        color: warehouse-oakland
        app: fulfillment
      annotations:
        config.linkerd.io/proxy-cpu-request: "0.5"
    spec:
      containers:
      - name: colorz
        image: ghcr.io/olix0r/colorwheel:v2
        ports:
        - containerPort: 8080
        env:
        - name: RUST_LOG
          value: info
        args:
        - paint
        - /colorwheel/paint/red.yml
        resources:
          requests:
            cpu: 5m
            memory: 5Mi
          limits:
            cpu: 500m
            memory: 50Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /colorwheel/paint
      volumes:
      - name: config-volume
        configMap:
          name: warehouse-config
          optional: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values: [zone-west]
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: fulfillment
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: warehouse-oakland
  namespace: orders
spec:
  maxReplicas: 9
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: warehouse-oakland
  targetCPUUtilizationPercentage: 20