apiVersion: v1
kind: Service
metadata:
  name: emoji-svc-2
  namespace: emojivoto
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prom
    port: 8801
    protocol: TCP
    targetPort: 8801
  selector:
    app: emoji-svc-2
  sessionAffinity: None
  type: ClusterIP

