gui:
  serviceType: LoadBalancer

face:
  errorFraction: 0
  delayBuckets: 0

backend:
  errorFraction: 0
  delayBuckets: 0

smiley:
  smiley: HeartEyes

smiley2:
  enabled: true
  smiley: RollingEyes

# smiley3:
#   enabled: true

color:
  color: green

color2:
  enabled: true
  color: red

# color3:
#   enabled: true
