---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  namespace: colorz
  labels:
    color: red
    app: paint
spec:
  replicas: 1
  selector:
    matchLabels:
      color: red
      app: paint
  template:
    metadata:
      labels:
        color: red
        app: paint
    spec:
      containers:
      - name: colorz
        image: ghcr.io/olix0r/colorwheel:v2
        ports:
        - containerPort: 8080
        env:
        - name: RUST_LOG
          value: info
        args:
        - paint
        - /colorwheel/paint/red.yml
        resources:
          requests:
            cpu: 10m # Overprovision
            memory: 10Mi
          limits:
            cpu: 1000m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /colorwheel/paint
      volumes:
      - name: config-volume
        configMap:
          name: paint-config
          optional: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values: [zone-0]