---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: smiley-route
  namespace: faces
spec:
  parentRefs:
    - kind: Service
      group: ""
      name: smiley
      namespace: faces
      port: 80
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /edge
      backendRefs:
        - kind: Service
          group: ""
          name: smiley2
          namespace: faces
          port: 80
    - backendRefs:
        - kind: Service
          group: ""
          name: smiley
          namespace: faces
          port: 80
