---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-chicago
  namespace: orders
  labels:
    color: warehouse-chicago
    app: fulfillment
spec:
  replicas: 1
  selector:
    matchLabels:
      color: warehouse-chicago
      app: fulfillment
  template:
    metadata:
      labels:
        color: warehouse-chicago
        app: fulfillment
      annotations:
        config.linkerd.io/proxy-cpu-request: "0.5"
    spec:
      containers:
      - name: colorz
        image: ghcr.io/olix0r/colorwheel:v3
        ports:
        - containerPort: 8080
        env:
        - name: RUST_LOG
          value: info
        args:
        - paint
        - /colorwheel/paint/green.yml
        resources:
          requests:
            cpu: 10m # Overprovision
            memory: 10Mi
          limits:
            cpu: 1000m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /colorwheel/paint
      volumes:
      - name: config-volume
        configMap:
          name: warehouse-config
          optional: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values: [zone-central]
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: warehouse-chicago
  namespace: orders
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: warehouse-chicago
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 90