apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: smiley-route
  namespace: faces
spec:
  parentRefs:
    - name: smiley
      kind: Service
      group: ""
      port: 80
  rules:
    - matches:
        - headers:
            - name: "x-faces-user"
              value: "flynn"
      backendRefs:
        - name: smiley3
          port: 80
    - backendRefs:
        - name: smiley
          port: 80
