apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/BuoyantIO/emojivoto/kustomize/deployment

patches:
  - path: web.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: web
  - path: emoji.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: emoji
  - path: voting.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: voting
  - path: vote-bot.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: vote-bot
